from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "files"
WINDOW_ICON_DIR = FILES_DIR / "calculadora.png"



BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE =  18

TEXT_MARGIN  = 10


PRIMARY_COLOR = "#3A86FF"
DARKER_PRIMARY_COLOR = "#2A6FD6"
DARKEST_PRIMARY_COLOR = "#1B4F99"